version: '3.7'

services:
  #
  # Paralink node
  #
  substrate-node:
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/paralink-node
    ports:
      - '30333:30333'
      - '9933:9933'
      - '9944:9944'
    expose:
      - '9944'
    environment:
      - CARGO_HOME=/var/www/paralink-node/.cargo
    volumes:
      - 'substrate-data:/data'
      - .:/var/www/paralink-node
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/paralink-node -d /data --pruning=archive --rpc-cors "*" --ws-port 9944 --port 30333 --unsafe-ws-external --no-prometheus --name 'Paralink explorer' --bootnodes /ip4/64.225.99.169/tcp/30334/p2p/12D3KooWNx6VZCvjKhAQfBqrMPZ3552gMS6TnyLEKCzyNpG8CT1y"
    restart: on-failure

  #
  # SQL data base
  #
  postgres:
    image: postgres
    restart: always
    volumes:
      - 'db-data:/var/lib/postgresql/data'
      - './sql/backend.sql:/docker-entrypoint-initdb.d/backend.sql'
    environment:
      POSTGRES_USER: 'paralink'
      POSTGRES_PASSWORD: 'paralink'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U paralink']
      interval: 5s
      timeout: 5s
      retries: 5
  #
  # Hasura GraphQL server
  #
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - '8082:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://paralink:paralink@postgres:5432/paralink
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  #
  # Chain crawler
  #
  crawler:
    image: crawler:latest
    build:
      context: ../../
      dockerfile: ./docker/backend/crawler/Dockerfile
    depends_on:
      - 'postgres'
      - 'substrate-node'
    restart: on-failure
    environment:
      - NODE_ENV=production
      - WS_PROVIDER_URL=ws://substrate-node:9944
      - SUBSTRATE_NETWORK=paralink
      # - CRAWLER_BLOCK_LISTENER_DISABLE=true
      # - CRAWLER_BLOCK_HARVESTER_DISABLE=true
#
# Persisten volumes
#
volumes:
  db-data: {}
  substrate-data: {}
